# Generated by Django 6.0.1 on 2026-03-02 22:44

import api_images.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenAlmacen',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=20)),
                ('origen_tipo', models.CharField(max_length=50)),
                ('origen_id', models.PositiveIntegerField()),
                ('paciente_id', models.PositiveIntegerField()),
                ('paciente_tipo', models.PositiveSmallIntegerField(choices=[(1, 'INTERNO'), (2, 'EXTERNO')], db_index=True, default=1)),
                ('archivo', models.ImageField(upload_to=api_images.models.ruta_imagen)),
                ('miniatura', models.ImageField(blank=True, null=True, upload_to=api_images.models.ruta_miniatura)),
                ('tipo_imagen', models.CharField(max_length=50)),
                ('tamaño', models.PositiveIntegerField()),
                ('formato', models.CharField(max_length=10)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('fecha_reemplazo', models.DateTimeField(blank=True, null=True)),
                ('usuario_creador', models.JSONField(blank=True, null=True)),
                ('usuario_desactivador', models.JSONField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['app', 'origen_tipo', 'origen_id', 'paciente_tipo', 'paciente_id', 'activo'], name='api_images__app_dde1f7_idx')],
            },
        ),
    ]
