# Generated by Django 6.0.1 on 2026-04-16 15:09

import api_images.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenUsuario',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_index=True, unique=True)),
                ('imagen', models.ImageField(upload_to=api_images.models.ruta_imagen_usuario)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
