# Generated by Django 6.0.1 on 2026-07-14 19:52

import api_images.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_images', '0002_imagenusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenDispositivo',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dispositivo_id', models.PositiveIntegerField()),
                ('archivo', models.ImageField(upload_to=api_images.models.ruta_imagen_dispositivo)),
                ('miniatura', models.ImageField(blank=True, null=True, upload_to=api_images.models.ruta_miniatura_dispositivo)),
                ('tipo_imagen', models.CharField(choices=[('GENERAL', 'General'), ('INVENTARIO', 'Inventario'), ('PLACA_SERIE', 'Placa o serie'), ('ESTADO_FISICO', 'Estado fisico'), ('ACCESORIOS', 'Accesorios'), ('OTRA', 'Otra')], max_length=50)),
                ('tamano', models.PositiveIntegerField()),
                ('formato', models.CharField(max_length=10)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('usuario_creador', models.JSONField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('dispositivo_id__gt', 0)), name='ck_imagen_dispositivo_id_positivo'), models.CheckConstraint(condition=models.Q(('tipo_imagen__in', ['GENERAL', 'INVENTARIO', 'PLACA_SERIE', 'ESTADO_FISICO', 'ACCESORIOS', 'OTRA'])), name='ck_imagen_dispositivo_tipo'), models.UniqueConstraint(fields=('dispositivo_id', 'tipo_imagen'), name='uq_imagen_dispositivo_tipo')],
            },
        ),
    ]
