# Generated by Django 6.0.1 on 2026-07-27

import api_images.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_images", "0003_imagendispositivo"),
    ]

    operations = [
        migrations.CreateModel(
            name="FichaBajaDispositivo",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("dispositivo_id", models.PositiveIntegerField(unique=True)),
                (
                    "archivo",
                    models.ImageField(
                        upload_to=api_images.models.ruta_ficha_baja_dispositivo,
                    ),
                ),
                (
                    "miniatura",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=(
                            api_images.models
                            .ruta_miniatura_ficha_baja_dispositivo
                        ),
                    ),
                ),
                ("tamano", models.PositiveIntegerField()),
                ("formato", models.CharField(max_length=10)),
                ("fecha_creado", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario_creador",
                    models.JSONField(blank=True, null=True),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("dispositivo_id__gt", 0)),
                        name="ck_ficha_baja_dispositivo_id_positivo",
                    ),
                ],
            },
        ),
    ]
