MAX_TAMANO_IMAGEN_MB = 15
TIPOS_PERMITIDOS = ["image/webp"]
ORIGEN_VALIDOS = ["EVALUACIONRXDETALLE", "REFERENCIA", "RESPUESTA"]
APP_VALIDAS = ["RX", "REFERENCIA"]
ESPACIO_TOTAL_ASIGNADO_BYTES = int(1.5 * 1024**4)  # 1.5 TB
